Reddit-Re-do/config/routes.rb
Rails.application.routes.draw do


  get 'comments/create'

  get 'comments/new'

  get 'comments/destroy'

  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :subs
  resources :posts, except: :index
  resources :comments, only: [:new, :create]
end

Reddit-Re-do/app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :author_id, :post_id, :content, presence: true

  belongs_to(
    :author,
    class_name: 'User',
    foreign_key: :author_id,
    primary_key: :id
  )

  belongs_to :post
end

Reddit-Re-do/app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, :author, presence: true
  validates :title, uniqueness: true

  belongs_to(
    :author,
    class_name: 'User',
    foreign_key: :author_id,
    primary_key: :id
  )

  # belongs_to :sub

  has_many :post_subs
  has_many :subs, through: :post_subs, source: :sub
  has_many :comments
end

Reddit-Re-do/app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :post, :sub_id, presence: true

  belongs_to :post, inverse_of: :post_subs
  belongs_to :sub

end

Reddit-Re-do/app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :moderator, :title, :description, presence: true
  validates :title, :description, uniqueness: true

  has_many :posts, dependent: :destroy

  belongs_to(
   :moderator,
   class_name: 'User',
   foreign_key: :moderator_id,
   primary_key: :id
  )

  has_many :post_subs
  # has_many :posts, through: :post_subs, source: :post

end

Reddit-Re-do/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :session_token, :username, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many(
    :posts,
    class_name: 'Post',
    foreign_key: :author_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :subs,
    class_name: 'Sub',
    foreign_key: :moderator_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :comments,
    class_name: 'Comment',
    foreign_key: :author_id,
    primary_key: :id
  )

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    return @user if @user && @user.is_password?(password)
    nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

Reddit-Re-do/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :all_subs
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def all_subs
    Sub.all
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end


end

Reddit-Re-do/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      flash[:alerts] = "Comment successfully posted"
      redirect_to post_url(@comment.post_id)
    else
      flash.now[:alerts] = @comment.errors.full_messages
      render :new
    end
  end

  def new
    @comment = Comment.new
  end

  def destroy
    @comment = Comment.find(params[:id])
    flash[:alerts] = "Comment deleted"
    post_id = @comment.post_id
    @comment.destroy
    redirect_to post_url(post_id)
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :author_id, :post_id,
                                    :parent_comment_id)
  end
end

Reddit-Re-do/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :verify_poster, only: [:edit, :update]

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash.now[:alerts] = ["#{@post.title} updated!"]
      render :show
    else
      flash.now[:alerts] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      flash.now[:alerts] = ["#{@post.title} created!"]
      render :show
    else
      flash.now[:alerts] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def new
    @post = Post.new
  end

  private

  def verify_poster
    @post = Post.find(params[:id])
    current_user.id == @post.author_id
  end

  def post_params
    params.require(:post).permit(:title, :body, :author_id, :sub_ids => [])
  end
end

Reddit-Re-do/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:alerts] = "Invalid username or password"
      redirect_to new_session_url
    else
      flash.now[:alerts] = "Welcome back!"
      login(user)
      redirect_to user_url(user)
    end
  end

  def new
    @user = User.new
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

Reddit-Re-do/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :verify_moderator, only: [:edit, :update]

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      flash.now[:alerts] = ["#{@sub.title} created!"]
      render :show
    else
      flash.now[:alerts] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update(sub_params)
      flash.now[:alerts] = ["#{@sub.title} updated!"]
      render :show
    else
      flash[:alerts] = @sub.errors.full_messages
      render :new
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    flash[:alerts] = ["#{@sub.title} deleted!"]
    @sub.destroy
    redirect_to subs_url
  end

  private

  def verify_moderator
    @sub = Sub.find_by(params[:id])
    current_user.id == @sub.moderator_id
  end

  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end
end

Reddit-Re-do/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      render :show
    else
      flash.now[:alerts] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
  end

  def destroy
  end

  def show
  end

  def edit
  end

  def update
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :session_token)
  end
end

Reddit-Re-do/app/helpers/comments_helper.rb
module CommentsHelper
end

Reddit-Re-do/app/helpers/posts_helper.rb
module PostsHelper
end

Reddit-Re-do/app/helpers/sessions_helper.rb
module SessionsHelper
end

Reddit-Re-do/app/helpers/subs_helper.rb
module SubsHelper
end

Reddit-Re-do/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action='<%= sub_url(@sub) %>' method='POST'>
  <input type='hidden' name='_method' value="put">
  <input type='hidden'
         name='authenticity_token'
         value='<%= form_authenticity_token%>' >

  <label for='title'>Title</label>
  <input type='text'
         name='sub[title]'
         id='title'
         value='<%=@sub.title%>'><br>

  <label for='description'>Description</label>
  <textarea
         name='sub[description]'
         id='description'> <%=@sub.description%> </textarea>

  <input type='submit' value='Update Subforum'>
</form>

Reddit-Re-do/app/views/subs/index.html.erb
<h3>All the subs!</h3>
<ol>
  <% @subs.each do |sub| %>
    <li><%= link_to "#{sub.title}: #{sub.description}", sub_url(sub) %></li>
  <% end %>
</ol>

<%= link_to "Create a Forum", new_sub_url %>

Reddit-Re-do/app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action='<%= subs_url %>' method='POST'>
  <input type='hidden'
         name='authenticity_token'
         value='<%= form_authenticity_token%>' >

  <label for='title'>Title</label>
  <input type='text'
         name='sub[title]'
         id='title'
         value='<%=@sub.title%>'><br>

  <label for='description'>Description</label><br>
  <textarea
         name='sub[description]'
         id='description'> <%=@sub.description%> </textarea><br>

  <input type='submit' value='Create Subforum'>
</form>

Reddit-Re-do/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h3>All the posts!</h3>
<ol>
  <% @sub.posts.each do |post| %>
    <li><%= link_to post.title, post_url(post) %></li>
  <% end %>
<br>

</ol>
<%= button_to 'Delete Sub', sub_url(@sub), method: :delete %>
<%= link_to "New Post", new_post_url %><br>
<%= link_to "Edit Forum", edit_sub_url(@sub) %><br>
<%= link_to "All Forums", subs_url %>

Reddit-Re-do/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

Reddit-Re-do/app/views/users/new.html.erb
<h1>Welcome, please sign up</h1>

<form action='<%= users_url %>' method='POST'>
  <input type='hidden'
         name='authenticity_token'
         value='<%= form_authenticity_token%>' >

  <label for='username'>Username</label>
  <input type='text'
         name='user[username]'
         id='username'
         value='<%=@user.username%>'><br>

  <label for='password'>Password</label>
  <input type='password'
         name='user[password]'
         id='password'><br>

  <input type='submit' value='Sign Up'>
</form>

Reddit-Re-do/app/views/users/show.html.erb
<h1><%= current_user.username %></h1>

<%= link_to "Check out the Subs!", subs_url %>
<br>
<%= link_to "Create a Subforum", new_sub_url %>