MusicLibrary/config/routes.rb
Rails.application.routes.draw do
  
  resources :notes

  resources :tracks, except: [:new, :index]

  resources :albums, except: [:new, :index] do
    resources :tracks, only: :new
  end

  resources :bands do 
    resources :albums, only: :new
  end

  root "bands#index"
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy] 
end

MusicLibrary/app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :band
	has_many :tracks, dependent: :destroy
end

MusicLibrary/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user!

  def show
    @album = Album.find(params[:id])
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new
  end

  def edit
    @album = Album.find(params[:id])
    @band = @album.band
  end

  def create
    band = Band.find(params[:album][:band_id])
    @album = band.albums.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @album = Album.find(params[:id])
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @band = @album.band
    @album.destroy
    respond_to do |format|
      format.html { redirect_to @band, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :live, :year)
    end
end

MusicLibrary/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicLibrary/app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :live %><br>
    <%= f.check_box :live %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.hidden_field :band_id, value: @band.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MusicLibrary/app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show this album', @album %> |
<%= link_to 'Back to ' + @album.band.name, band_url(@album.band) %>

MusicLibrary/app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Live</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.name %></td>
        <td><%= album.live %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

MusicLibrary/app/views/albums/new.html.erb
<h1>New <%= @band.name %> Album! </h1>

<%= render 'form' %>

<%= link_to 'Back to ' + @band.name, band_url(@band) %>

MusicLibrary/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Live:</strong>
  <%= @album.live %>
</p>

<p>
  <strong>Year:</strong>
  <%= @album.year %>
</p>

<p>
  <strong>Band:</strong>
  <%= @album.band.name %>
</p>

<p>
  <strong>Tracks:</strong>
  <ul>
    <% @album.tracks.each do |track| %>
      <li><%= link_to track.name, track_url(track) %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Add a track', new_album_track_url(@album) %><br>
<%= link_to 'Edit this album', edit_album_url(@album) %><br>
<%= link_to 'Delete this album', album_url(@album), method: :delete %><br>
<%= link_to 'See all albums from ' + @album.band.name, band_url(@album.band) %>